name: CodeCov

on: 
  - push
  - pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.10'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m unittest test/test.py
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2