name: CodeCov

on: 
  - push
  - pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.10'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Generate Report
      run: |
        pip install coverage
        coverage run --source=jspec -m unittest test/test.py
        coverage json --omit=jspec/parse.py,jspec/check.py
    - name: Store coverage file
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage.json
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
    - name: Publish CodeCov badge
      run: |
        curl "https://img.shields.io/badge/coavrege-100%25-green" > badge.svg